---
- hosts: all
  connection: local
  become: true
  user: vagrant
  tasks:
    - name: Install the libselinux-python package
      yum: name=libselinux-python state=latest
    - name: disable selinux
      selinux: state=disabled
    - name: stop iptables
      service: name=iptables state=stopped enabled=no
    - incluede: install_amp.yaml
